name: Deploy Todo App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Self-Hosted Server
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy application
        run: |
          deploy todo-app-next
        shell: bash